# Where the dependencies are installed to. This will be relative to the rucksack.toml file.
# If not specified, the default is "packages".
path = "packages"

# Types of dependencies:
# - git: A git repository. The path is the URL to the repository, can include tags through the # syntax.
# - zip: A zip file. The path is the URL to the zip file.
# - tar: A tar file. The path is the URL to the tar file.
[dependencies]
# vide = "git https://github.com/centau/vide.git"
# sdl3_source = "tar https://github.com/libsdl-org/SDL/releases/download/release-3.2.12/SDL3-3.2.12.tar.gz"
# sdl3_rel_windows = "zip https://github.com/libsdl-org/SDL/releases/download/release-3.2.12/SDL3-3.2.12-win32-x64.zip"
