name: Release

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  prep:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.15.0-dev.460+f4e9846bc

      - name: Get Version
        id: version
        run: |
          version=$(zig build version)
          echo "version=$version">> $GITHUB_OUTPUT

  build:
    needs: prep
    strategy:
      matrix:
        include:
          - name: linux x86_64
            target: x86_64-linux-gnu
            artifact: rucksack-${{ needs.prep.outputs.version }}-linux-x86_64
          - name: linux arm64
            target: aarch64-linux-gnu
            artifact: rucksack-${{ needs.prep.outputs.version }}-linux-aarch64
          - name: linux RISCV64
            target: riscv64-linux
            artifact: rucksack-${{ needs.prep.outputs.version }}-linux-riscv64
          - name: windows x86_64
            target: x86_64-windows
            artifact: rucksack-${{ needs.prep.outputs.version }}-windows-x86_64
            ext: .exe
          - name: windows arm64
            target: aarch64-windows
            artifact: rucksack-${{ needs.prep.outputs.version }}-windows-aarch64
            ext: .exe
          # disable for now until CommonCrypto/CommonCrypto.h is included
          # - name: macos arm64
          #   target: aarch64-macos
          #   artifact: rucksack-${{ needs.prep.outputs.version }}-macos-aarch64

    name: ${{ matrix.name }}
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.15.0-dev.460+f4e9846bc

      - name: Build
        run: zig build -Dtarget=${{ matrix.target }} -Doptimize=ReleaseFast

      - name: Copy binaries to root
        run: cp -r ./zig-out/* .

      - name: Pack Artifact
        run: zip -r ${{ matrix.artifact }}.zip ./bin

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}.zip

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [prep, build]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # draft: true
          files: |
            ./artifacts/*.zip
          name: ${{ needs.prep.outputs.version }}
          tag_name: v${{ needs.prep.outputs.version }}
          fail_on_unmatched_files: true
